### ISSUE TITLE
FotoapparatBuilder does not accept a focus view in latest official release.

### ISSUE THREAD

**Issue by noelnv** [RedApparat/Fotoapparat#246]
I noticed that in v2.2.0, the Fotoapparat constructor supports a FocusView parameter, but FotoApparatBuilder will not accept a FocusView.

This makes the feature hard to use, as callers have to either start calling the constructor directly, or they have to make their own builder class.

I noticed this has been updated in master.  Is there a release pending which will include this change?

Thanks for a great library!

**Comment by Diolor** [comment]
Took us a while because life happened but v2.3.0 is out  🙌
