### ISSUE TITLE
How to use this with Google Mobile Vision API

### ISSUE THREAD

**Issue by etsushisa** [RedApparat/Fotoapparat#268]
What's the idea if I want to use `Google Mobile Vision API` with `Fotoapparat`
https://developers.google.com/vision/

**Comment by Diolor** [comment]
What do you mean by idea?

**Comment by etsushisa** [comment]
@Diolor Sorry for my poor English
Is there any way to use `Google Mobile Vision API` with `Fotoapparat` together?

**Comment by Diolor** [comment]
You can use FA's frameprocessor to extract frames which you can later analyze with Google MV API.
https://github.com/RedApparat/Fotoapparat/wiki/Configuration-Kotlin

Obviously there will be no visual feedback because we have no such support here. :)

**Comment by etsushisa** [comment]
@Diolor I see, sorry, I missed that, thank you so much!
