### ISSUE TITLE
2.3.0 version is missing from jitpack

### ISSUE THREAD

**Issue by mateherber** [RedApparat/Fotoapparat#269]
#### What are you trying to achieve or the steps to reproduce?

Update the library to latest 2.3.0 version

#### What was the result you received?

Library version was not found on jitpack

#### What did you expect?

Updating to 2.3.0 succeeds

#### Context:

* *FA version*: 2.3.0

**Comment by hegazy** [comment]
Same here `Failed to resolve: io.fotoapparat.fotoapparat:library:2.3.0`
https://jitpack.io/com/github/RedApparat/Fotoapparat/2.3.0/build.log

**Comment by Diolor** [comment]
Jitpack just successfully built it thanks to @hegazy's PR 🙌
