### ISSUE TITLE
When taking a picture, I want to it has voice,like system camera, how can I do it? Thank you!

### ISSUE THREAD

**Issue by mumuyan** [RedApparat/Fotoapparat#270]

**Comment by Diolor** [comment]
You have to implement the sounds yourself

**Comment by mumuyan** [comment]
Thank you for your reply. But I can't find a method to implement, I find Fotoapparat class don't provide the method for this.  whether I need to get Camera object and then implement it. Could you give me a example? Thanks.

**Comment by Diolor** [comment]
When you call `fotoapparat.takePicture()` you should also play the sound.
