### ISSUE TITLE
Setting null FrameProcessor in updateConfiguration() still starts frames processing. Some devices receive null preview frames which causes IllegalStateException.

### ISSUE THREAD

**Issue by xaeon** [RedApparat/Fotoapparat#280]
When i call the Fotoapparat.updateConfiguration() function, i set frameProcessor = null (the default value). But inside the library, the PreviewStream.updateProcessorSafely() function is still called with an empty, but not null, FrameProcessor. So this function starts frame processing. There is no problems other than increased resources consumption. 

But on the ZTE BLADE A520 device, PreviewCallback.onPreviewFrame() get called with null data parameter. When it get passed to PreviewStream.dispatchFrameOnBackgroundThread function, a  "java.lang.IllegalStateException: data must not be null" is thrown

**Comment by wilsonrc** [comment]
@xaeon I think I have the same Issue with a Samsung Galaxy Grand Prime with Android 7.1, do you already have any solution for this?

**Comment by wilsonrc** [comment]
@dmitry-zaitsev can you help us with this?

**Comment by dmitry-zaitsev** [comment]
Thanks for reporting it. It should be fixed by this PR:

https://github.com/RedApparat/Fotoapparat/pull/284

You can expect a new version in 2 days.

**Comment by dmitry-zaitsev** [comment]
The fix is available in version 2.3.3.
