### ISSUE TITLE
How to pause/resume preview?

### ISSUE THREAD

**Issue by sevar83** [RedApparat/Fotoapparat#281]
Hi, I wish to pause the preview stream for a couple of seconds. I don't want to completely stop it but very quickly toggle pause/resume.

**Comment by Diolor** [comment]
Stopping and starting again FA is not a very expensive task. It's also fairly fast, no?

**Comment by sevar83** [comment]
I had the sensation that the initial startup is quite heavy as it causes a little bit of flash and delay on my S9. But I'll give it a try.
