### ISSUE TITLE
Testing with Espresso

### ISSUE THREAD

**Issue by sevar83** [RedApparat/Fotoapparat#282]
Hi, we've successfully used Fotoapparat in an interesting OCR-related project. It's absolutely kick-ass. But now our QA team wish to write automated integration tests with Espresso and need to stub the result photo. Any advice how to mock the camera cleanly and properly? I prefer to not mock Fotoapparat but the underlying camera.

**Comment by Diolor** [comment]
Hi and thanks for your kind words. My two cents on testing:

I think if you mock FA and the returning result will be sufficient for you. Let me explain: If you mock the vanilla camera API then you will also test FA. In practice it's our responsibility to test FA here, so it might be unnecessary work from you. If you mock FA you will approach it as a "stable API black box" and only test your logic, which is what matters there.

If you still want to mock the Android camera API then you have to read the FA source code and mock all the points FA touches the Android camera API
