### ISSUE TITLE
Videoapparat dead?

### ISSUE THREAD

**Issue by RAN3000** [RedApparat/Fotoapparat#285]
Hey, I've been using Fotoapparat for a while with great pleasure.
I wanted to add video recording to my app, but the link [fotoapparat.io](fotoapparat.io) is dead, and I don't see much activity on the Videoapparat repo.
Are you guys still working on it? Are there future plans for video recording? What are possible alternatives?

**Comment by Diolor** [comment]
Yes, it's dead and plans are unknown for it so far. Sorry for the bad news
