### ISSUE TITLE
Problems adding as a module

### ISSUE THREAD

**Issue by robyy72** [RedApparat/Fotoapparat#300]
Hi,
I tried to add fotoapparat as a module to a new, empty project api target level 28.

Error:

Element: class org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileImpl because: different providers: SingleRootFileViewProvider{myVirtualFile=file://C:/Users/haupt/AndroidStudioProjects/Fototest4/settings.gradle, content=VirtualFileContent{size=16}}(4eaea5f4); SingleRootFileViewProvider{myVirtualFile=file://C:/Users/haupt/AndroidStudioProjects/Fototest4/settings.gradle, content=VirtualFileContent{size=16}}(553ba981)

Any ideas ?

Best regards
Robert

**Comment by dmitry-zaitsev** [comment]
Unfortunately I can't help you here, never encountered such problem.

What is your use case? Why not just taking the latest version from jcenter()?
