### ISSUE TITLE
Custom photoResolution

### ISSUE THREAD

**Issue by Corical** [RedApparat/Fotoapparat#304]
Not an issue but question on how to get a custom resolution, something along the lines of 800x600, we don't want highest resolution and lowest is too low, something in between otherwise the pictures take up a lot of space and we're definitely not sending 4mb a pop (highest reso).

Should I take them at high reso and scale them down manually ?

PS: This is in Java.

**Comment by Diolor** [comment]
It's not possible. Simply if a phone camera doesn't support e.g. 800x600, you can't have it. You can always take a bigger one and downscale it by yourself.

**Comment by Gnzlt** [comment]
How do I know if the phone camera doesn't support `800x600` beforehand?

**Comment by Diolor** [comment]
@Gnzlt 
https://github.com/RedApparat/Fotoapparat/blob/master/fotoapparat/src/main/java/io/fotoapparat/Fotoapparat.kt#L128
