### ISSUE TITLE
Cannot load Fotoapparat on Kotlin 1.3

### ISSUE THREAD

**Issue by bmachimbira** [RedApparat/Fotoapparat#314]
I migrated my existing application that uses Fotoapparat for the camera. The application compiles successfully but I get the following error:

`java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/CompletableDeferredKt;
        at io.fotoapparat.hardware.CameraDevice.<init>(CameraDevice.kt:48)
        at io.fotoapparat.hardware.Device.<init>(Device.kt:39)
        at io.fotoapparat.hardware.Device.<init>(Device.kt:34)
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:55)
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:48)`

I think this is because the library uses the experimental coroutines module, which has been removed from Kotlin 1.3.

I am using version 2.5.0 of Fotoapparat.

**Comment by geminixandroid** [comment]
Same issue

**Comment by limuyang2** [comment]
Same issue

**Comment by limuyang2** [comment]
coroutines error

**Comment by limuyang2** [comment]
my version is `implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.0'`

**Comment by vicobz** [comment]
Same issue. Need a fix asap! :)

**Comment by AshuTyagi16** [comment]
Same Issue. please fix.

**Comment by dmitry-zaitsev** [comment]
I will take a look and try to release a new version today. Latest, tomorrow.
