### ISSUE TITLE
Could not find io.fotoapparat:fotoapparat:2.6.0.

### ISSUE THREAD

**Issue by Laces** [RedApparat/Fotoapparat#316]
In the readme, it says I have to add `implementation 'io.fotoapparat:fotoapparat:2.6.0'` to my gradle file, but gradle could not find io.fotoapparat:fotoapparat:2.6.0,
When do you plan to create a new release?

**Comment by fleficher** [comment]
Hi, seems that `2.6.0` version is not fully published yet. Meanwhile, you can use the `2.5.0`.

**Comment by dmitry-zaitsev** [comment]
It was just deployed, sorry for the inconvenience.

**Comment by vicobz** [comment]
I still face 
> Failed to resolve: io.fotoapparat.fotoapparat:library:2.6.0

Am i missing something?

**Comment by dmitry-zaitsev** [comment]
@vicobz it should be `io.fotoapparat:fotoapparat:2.6.0`, not `io.fotoapparat.fotoapparat:library:2.6.0`

**Comment by vicobz** [comment]
I was so missing something 😉
Thanks for your quick reply!
