### ISSUE TITLE
freeze when takephoto and convert to bitmap

### ISSUE THREAD

**Issue by RowanG1** [RedApparat/Fotoapparat#336]
When I use the code:
fotoapparat?.takePicture()?.toBitmap(),

the preview freezes for about one second. Is there any way to overcome this? I am testing on a Xiaomi device, MiA1. I am using a timer to capture the image every 2 seconds.

**Comment by Diolor** [comment]
Migration to Camera 2 is the only way which is currently not in the roadmap.

**Comment by shedeed1** [comment]
I managed to get around this issue by using RxJava and subscribing on IO thread.

Disposable disposable = fotoapparat.takePicture()
                            .toBitmap()
                            .adapt(SingleAdapter.<BitmapPhoto>toSingle())
                            .subscribeOn(Schedulers.io())
                            .subscribe(new Consumer<BitmapPhoto>() ......
