### ISSUE TITLE
CameraView: How to create CameraView Object programmatically

### ISSUE THREAD

**Issue by sharma4frnds** [RedApparat/Fotoapparat#342]
CameraView: How to create CameraView Object programmatically, if i dont want to use <io.fotoapparat.view.CameraView
        android:id="@+id/camera_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
in my code, please share some sample code.

**Comment by Diolor** [comment]
Like any other custom view: `CameraView(context)`
