### ISSUE TITLE
How can i apply converted frame to preview/photoResult

### ISSUE THREAD

**Issue by mym0404** [RedApparat/Fotoapparat#345]
#### What are you trying to achieve or the steps to reproduce?

Hi I want to apply filter/flip/other image processing to preview/photoResult

I know this things are not work of this library.

I want to know is that 

1. I converted byte array to converted byte array or bitmap in frameProcessing{}

2. how can i apply this image to preview and captured photo?

I know this is stupid question... Sorry about that

#### What was the result you received?

convert frame.image to converted byte array not affected..

#### Context:

* *FA version*:
* *Devices/APIs affected*:
* *any other relevant information*:

**Comment by mym0404** [comment]
I solved my problem with Frame Processor.

Frame Processor can't handle preview itself.

So I did like below.

1. convert byte[] (YUV format) to image 

2. processing image (OpenGL)

3. Show Image using other GLSurfaceView

4. Turn off CameraView of this library (turn off setPreviewTexture & setPreviewSurface?)

Then, I can receive only byte[] data from this great library.

**Comment by kleysonr** [comment]
Hi @mym0404,

May you share the final layout and your FrameProcessor class ? I am a newbie on android dev and I need to achieve the same as you.

Thanks.
