### ISSUE TITLE
Memory Leak when updateConfiguration()

### ISSUE THREAD

**Issue by mym0404** [RedApparat/Fotoapparat#346]
When is use updateConfiguration for turn flash mode (torch(), off())

addFrameWithBuffer() method made memory leak.

and i recognized that 

start() method is called 3~4 times at once.

So I just changed some code like below.

```kotlin
fun updateProcessorSafely(frameProcessor: FrameProcessor?) {
        if(!frameProcessors.isEmpty())
            return
        clearProcessors()
        if (frameProcessor == null) {
            stop()
        } else {
            addProcessor(frameProcessor)
            start()
        }
    }
```

Sorry about ugly preview. I am newbie on Github.

I use single same frame processor, so i have no reason to update processor at updateConfiguartion() call

**Comment by army650663** [comment]
Same problem!
